package com.localbuddy.notification;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_ACCEPTED,
    BOOKING_DECLINED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    BOOKING_UPDATED,
    GUEST_BOOKING_CREATED,
    SAFETY_REPORT_CREATED,
    SAFETY_REPORT_RESOLVED,
    LOCAL_PROFILE_SUBMITTED,
    LOCAL_PROFILE_APPROVED,
    LOCAL_PROFILE_CHANGES_REQUESTED,
    LOCAL_PROFILE_REJECTED,
    SYSTEM_ALERT
}